### ISSUE TITLE
Show a warning message when a page definition that is used by a test case(s) and/or a test routine(s) is being deleted

### ISSUE THREAD

**Issue by brogreenmoon** [rockmelonqa/rockmelonqa-ide#147]
Show the message "This page definition is being used by the following test cases and test routines. Do you want to remove it? [list the test cases and routines that are using this page definition]" when deleting a page definition that is referenced by one or more test cases and/or test routines.

Currently the page definition is deleted without a warning, and the page references are simply removed from the test case:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/e5c1e823-9a0b-4f12-a200-3987d7c18ed9)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/5a791071-1358-40ef-b748-d367fad8f635)

Which in turn causes a codegen error that is very difficult to troubleshoot:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/8f79a781-9a71-4cf8-9984-0e07f7fdaf47)

**Comment by brogreenmoon** [comment]
The message is good:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/72efe98d-5366-4e7c-bfa0-1bc897ef54b2)

but you should still be able to delete the page, i.e. ask "Do you want to remove it?" with [Yes]  [No] buttons.  Right now you can only cancel and never delete the page.

**Comment by quockhanh** [comment]
I think user should delete page/page element out of test case/test routine **manually**. That is our design

It is different from confirmation and auto delete test case our of test suite <-- because this one does not affect to anything
However, deleting page/page element out of test case automatically (via YES button of confirmation message) would affect strongly to whole test case/test routine. User cannot undo it, and it's good to let them go back to review and delete page/page element **manually**

It looks like when you drop columns or tables which are being referenced by the other (example foreign key). You must manually solve that issue first then run delete statement again
